version: "3.8"

services:
  excalidraw:
    stdin_open: true
    build:
      context: .
      target: production
    container_name: excalidraw
    ports:
      - "5010:3000"
    restart: always
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=production
      - NGINX_PORT=3000
  excalidraw-storage-backend:
    build:
      context: https://github.com/kitsteam/excalidraw-storage-backend.git#main
      target: production
    ports:
      - "5011:8080"
    restart: always
    environment:
      STORAGE_URI: redis://:${REDIS_PASSWORD}@redis:6379
      STORAGE_TTL: 2592000000

  excalidraw-room:
    image: excalidraw/excalidraw-room
    restart: always
    ports:
      - "5012:80"
  
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis_data:/data

volumes:
  notused:
  redis_data:
